apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-service-production
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    path: examples/kustomize/my-service/overlay/production
    repoURL: https://github.com/dag-andersen/argocd-diff-preview
    kustomize:
      patches:
        - target:
            kind: Deployment
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/ports/0/containerPort
              value: 443