apiVersion: v1
kind: Secret
metadata:
  name: integration-test-repository-secret
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/dag-andersen/argocd-diff-preview.git
