apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: level-1c-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: prod
          - env: staging
  template:
    metadata:
      name: "level-1c-{{env}}-app"
      namespace: argocd
    spec:
      project: default
      destination:
        name: in-cluster
        namespace: default
      source:
        repoURL: https://github.com/dag-andersen/argocd-diff-preview
        path: "examples/app-of-apps/apps/level-1c-{{env}}"
