apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sympozium-agent-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sympozium-agent-node-reader
subjects:
  - kind: Group
    name: "aks:jwt:eks-platformservices-prod:system:serviceaccount:sympozium-system:sympozium-agent"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sympozium-agent-node-reader
  apiGroup: rbac.authorization.k8s.io
