apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: dev
      - name: prod
      - name: staging
  template:
    metadata:
      name: 'my-app-set-{{.name}}'
    spec:
      project: default
      destination:
        name: in-cluster
        namespace: default
      sources:
        - repoURL: https://github.com/dag-andersen/argocd-diff-preview
          ref: local-files
        - path: examples/helm/charts/myApp
          repoURL: https://github.com/dag-andersen/argocd-diff-preview
          helm:
            valueFiles:
              - $local-files/examples/helm/values/my-app-set.yaml