apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-change-example-sfs-1
spec:
  serviceName: order-change-example-sfs-1
  replicas: 2
  selector:
    matchLabels:
      app: example-sfs-1
  template:
    metadata:
      labels:
        app: example-sfs-1
    spec:
      containers:
        - name: myapp
          image: dag-andersen/myapp:latest
          ports:
            - containerPort: 80
