apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: level-2c-app
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/dag-andersen/argocd-diff-preview
    path: examples/app-of-apps/apps/level-2c
