# Overrides done by argocd-diff-preview
# These will happen BEFORE the values.yaml file is loaded
notifications:
  enabled: false
dex:
  enabled: false
configs:
  params:
    application.namespaces: "*"