# Overrides done by argocd-diff-preview
# These will happen after the values.yaml file is loaded
notifications:
  enabled: false
dex:
  enabled: false
configs:
  params:
    reposerver.git.request.timeout: "150s"