# Overrides done by argocd-diff-preview
# These will happen after the values.yaml file is loaded
notifications:
  enabled: false
dex:
  enabled: false
applicationSet:
  replicas: 0
# Explicitly disable the source hydrator / commit server
# We don't want ArgoCD to push hydrated manifests to git
# Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/source-hydrator/#enabling-the-source-hydrator
configs:
  params:
    hydrator.enabled: "false"
# Readiness probe settings have been adjusted to start checks immediately (initialDelaySeconds: 0)
# The failureThreshold is increased to ensure the total time before a pod is marked unhealthy remains similar to the default
# This default duration is calculated using the original values from values.yaml for (initialDelaySeconds + failureThreshold * periodSeconds)
server:
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 40
repoServer:
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 40
  # This prevents 'empty index.yaml' file corruption issues when multiple helm dependency build processes try to write the same index.yaml file
  # Setting this to false disables the shared working dir
  # Ref: https://github.com/argoproj/argo-cd/issues/12902
  # Ref: https://github.com/helm/helm/issues/10735#issuecomment-1486058169
  useEphemeralHelmWorkingDir: false
controller:
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 40
  roleRules:
    - apiGroups:
        - "*"
      resources:
        - "*"
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - argoproj.io
      resources:
        - applications
        - applications/status
      verbs:
        - get
        - list
        - watch
        - update
        - patch