apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  sources:
    - chart: ingress-nginxxx
      repoURL: "https://kubernetes.github.io/ingress-nginx"
      targetRevision: 4.10.0
      helm:
        valuesObject:
          controller:
            ingressClass: "test"
