apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: duplicate-generated-apps
  namespace: argocd-diff-preview
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: dupe
            path: examples/duplicate-generated-apps/resources
          - name: dupe
            path: examples/duplicate-generated-apps/resources
  template:
    metadata:
      name: "{{ .name }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/dag-andersen/argocd-diff-preview.git
        path: "{{ .path }}"
      destination:
        name: in-cluster
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
