apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: refactoring-appset-example
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: production
      - env: staging
  template:
    metadata:
      name: 'refactoring-appset-example-{{.env}}'
    spec:
      project: default
      destination:
        name: in-cluster
        namespace: 'refactoring-appset-example-{{.env}}'
      source:
        repoURL: https://github.com/dag-andersen/argocd-diff-preview
        targetRevision: HEAD
        path: 'examples/use-cases/refactoring/my-service/overlay/{{.env}}/'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true