apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: myapp
          image: dag-andersen/myapp:latest
          ports:
            - containerPort: 80
