apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-custom-target-revision
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - path: examples/helm/charts/myApp
      repoURL: https://github.com/dag-andersen/argocd-diff-preview
      targetRevision: v0.0.31
      helm:
        valuesObject:
          replicaCount: 2