apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-from-folder-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: dag-andersen/myapp:latest
          ports:
            - containerPort: 80
