name: Tests and release

on:
  push:
    tags:
      - "v*.*.*"
env:
  CRATE_NAME: argocd-diff-preview
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.platform.os_name }} with rust
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: argocd-diff-preview
            name: argocd-diff-preview-Linux-x86_64-musl.tar.gz
          - os_name: Linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: argocd-diff-preview
            name: argocd-diff-preview-Linux-aarch64-musl.tar.gz
          - os_name: Linux-arm
            os: ubuntu-20.04
            target: arm-unknown-linux-musleabi
            bin: argocd-diff-preview
            name: argocd-diff-preview-Linux-arm-musl.tar.gz
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: argocd-diff-preview
            name: argocd-diff-preview-Darwin-x86_64.tar.gz
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: argocd-diff-preview
            name: argocd-diff-preview-Darwin-aarch64.tar.gz
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Install musl-tools on Linux
        if: contains(matrix.platform.name, 'musl')
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: "--locked --release"
          strip: true
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: argocd-diff-preview-${{ matrix.platform.os_name }}
          path: "argocd-diff-preview-*"
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "argocd-diff-preview-*"
        if: startsWith( github.ref, 'refs/tags/v' )
